const languages = [
  {
    no: "0",
    name: "Auto",
    native: "Detect",
    code: "auto",
  },
  {
    no: "1",
    name: "Afrikaans",
    native: "Afrikaans",
    code: "af",
  },
  {
    no: "2",
    name: "Albanian",
    native: "Shqip",
    code: "sq",
  },
  {
    no: "3",
    name: "Arabic",
    native: "عربي",
    code: "ar",
  },
  {
    no: "4",
    name: "Armenian",
    native: "Հայերէն",
    code: "hy",
  },
  {
    no: "5",
    name: "Azerbaijani",
    native: "آذربایجان دیلی",
    code: "az",
  },
  {
    no: "6",
    name: "Basque",
    native: "Euskara",
    code: "eu",
  },
  {
    no: "7",
    name: "Belarusian",
    native: "Беларуская",
    code: "be",
  },
  {
    no: "8",
    name: "Bengali",
    native: "বাংলা",
    code: "bn",
  },
  {
    no: "9",
    name: "Bulgarian",
    native: "Български",
    code: "bg",
  },
  {
    no: "10",
    name: "Catalan",
    native: "Català",
    code: "ca",
  },
  {
    no: "11",
    name: "Chinese (Simplified)",
    native: "中文简体",
    code: "zh-CN",
  },
  {
    no: "12",
    name: "Chinese (Traditional)",
    native: "中文繁體",
    code: "zh-TW",
  },
  {
    no: "13",
    name: "Croatian",
    native: "Hrvatski",
    code: "hr",
  },
  {
    no: "14",
    name: "Czech",
    native: "Čeština",
    code: "cs",
  },
  {
    no: "15",
    name: "Danish",
    native: "Dansk",
    code: "da",
  },
  {
    no: "16",
    name: "Dutch",
    native: "Nederlands",
    code: "nl",
  },
  {
    no: "17",
    name: "English",
    native: "English",
    code: "en",
  },
  {
    no: "18",
    name: "Estonian",
    native: "Eesti keel",
    code: "et",
  },
  {
    no: "19",
    name: "Filipino",
    native: "Filipino",
    code: "tl",
  },
  {
    no: "20",
    name: "Finnish",
    native: "Suomi",
    code: "fi",
  },
  {
    no: "21",
    name: "French",
    native: "Français",
    code: "fr",
  },
  {
    no: "22",
    name: "German",
    native: "Deutsch",
    code: "de",
  },
  {
    no: "23",
    name: "Gujarati",
    native: "ગુજરાતી",
    code: "gu",
  },
  {
    no: "24",
    name: "Hebrew",
    native: "עברית",
    code: "iw",
  },
  {
    no: "25",
    name: "Hindi",
    native: "हिन्दी",
    code: "hi",
  },
  {
    no: "26",
    name: "Hungarian",
    native: "Magyar",
    code: "hu",
  },
  {
    no: "27",
    name: "Indonesian",
    native: "Bahasa Indonesia",
    code: "id",
  },
  {
    no: "28",
    name: "Italian",
    native: "Italiano",
    code: "it",
  },
  {
    no: "29",
    name: "Japanese",
    native: "日本語",
    code: "ja",
  },
  {
    no: "30",
    name: "Kannada",
    native: "ಕನ್ನಡ",
    code: "kn",
  },
  {
    no: "31",
    name: "Korean",
    native: "한국어",
    code: "ko",
  },
  {
    no: "32",
    name: "Latvian",
    native: "Latviešu",
    code: "lv",
  },
  {
    no: "33",
    name: "Lithuanian",
    native: "Lietuvių kalba",
    code: "lt",
  },
  {
    no: "34",
    name: "Malayalam",
    native: "മലയാളം",
    code: "ml",
  },
  {
    no: "35",
    name: "Marathi",
    native: "मराठी",
    code: "mr",
  },
  {
    no: "36",
    name: "Mongolian",
    native: "Монгол",
    code: "mn",
  },
  {
    no: "37",
    name: "Nepali",
    native: "नेपाली",
    code: "ne",
  },
  {
    no: "38",
    name: "Norwegian",
    native: "Norsk",
    code: "no",
  },
  {
    no: "39",
    name: "Polish",
    native: "Polski",
    code: "pl",
  },
  {
    no: "40",
    name: "Portuguese",
    native: "Português",
    code: "pt",
  },
  {
    no: "41",
    name: "Punjabi",
    native: "ਪੰਜਾਬੀ",
    code: "pa",
  },
  {
    no: "42",
    name: "Romanian",
    native: "Română",
    code: "ro",
  },
  {
    no: "43",
    name: "Russian",
    native: "Русский",
    code: "ru",
  },
  {
    no: "44",
    name: "Serbian",
    native: "Српски",
    code: "sr",
  },
  {
    no: "45",
    name: "Spanish",
    native: "Español",
    code: "es",
  },
  {
    no: "46",
    name: "Swahili",
    native: "Kiswahili",
    code: "sw",
  },
  {
    no: "47",
    name: "Swedish",
    native: "Svenska",
    code: "sv",
  },
  {
    no: "48",
    name: "Tamil",
    native: "தமிழ்",
    code: "ta",
  },
  {
    no: "49",
    name: "Telugu",
    native: "తెలుగు",
    code: "te",
  },
  {
    no: "50",
    name: "Thai",
    native: "ไทย",
    code: "th",
  },
  {
    no: "51",
    name: "Turkish",
    native: "Türkçe",
    code: "tr",
  },
  {
    no: "52",
    name: "Ukrainian",
    native: "Українська",
    code: "uk",
  },
  {
    no: "53",
    name: "Urdu",
    native: "اردو",
    code: "ur",
  },
  {
    no: "54",
    name: "Vietnamese",
    native: "Tiếng Việt",
    code: "vi",
  },
  {
    no: "55",
    name: "Chinese (Hong Kong)",
    native: "繁體中文（香港）",
    code: "zh-HK",
  },
  {
    no: "56",
    name: "Malay",
    native: "Bahasa Melayu",
    code: "ms",
  },
  {
    no: "57",
    name: "Bengali (India)",
    native: "বাংলা (ভারত)",
    code: "bn-IN",
  },
  {
    no: "58",
    name: "Hausa",
    native: "Hausa",
    code: "ha",
  },
  {
    no: "59",
    name: "Igbo",
    native: "Igbo",
    code: "ig",
  },
  {
    no: "60",
    name: "Swahili",
    native: "Kiswahili",
    code: "sw",
  }
];
